const KANDD_SUPABASE_URL='https://hfqallzmxsmkiqmolzui.supabase.co';
const KANDD_SUPABASE_KEY='sb_publishable_O7ZvBkAu8JH939O0ylNOkA_Y7aYEnQr';
const kanddDb=window.supabase.createClient(KANDD_SUPABASE_URL,KANDD_SUPABASE_KEY);
async function kanddUser(){const {data}=await kanddDb.auth.getUser();return data.user||null}
async function kanddProfile(){const u=await kanddUser();if(!u)return null;const {data}=await kanddDb.from('profiles').select('*').eq('user_id',u.id).maybeSingle();return data}
async function kanddSignOut(){await kanddDb.auth.signOut();location.href='index.html'}
async function kanddSaveProgress(itemType,itemKey,completed=false,score=null,metadata={}){const u=await kanddUser();if(!u)return false;const row={user_id:u.id,item_type:itemType,item_key:itemKey,completed,score,metadata,updated_at:new Date().toISOString()};const {error}=await kanddDb.from('progress').upsert(row,{onConflict:'user_id,item_type,item_key'});if(error){console.error(error);return false}return true}
async function kanddLoadProgress(){const u=await kanddUser();if(!u)return [];const {data,error}=await kanddDb.from('progress').select('*').eq('user_id',u.id);if(error){console.error(error);return []}return data||[]}
async function kanddImportLocalProgress(){const u=await kanddUser();if(!u)return {ok:false,count:0};let rows=[];for(let n=1;n<=12;n++){let score=localStorage.getItem('lesson'+n+'Score');let complete=localStorage.getItem('lesson'+n+'Complete')==='yes';if(score!==null||complete)rows.push({user_id:u.id,item_type:'lesson',item_key:String(n),completed:complete,score:score===null?null:Number(score),metadata:{source:'browser-import'},updated_at:new Date().toISOString()})}for(const [key,item] of [['review14Complete','checkpoint-1'],['review58Complete','checkpoint-2'],['finalAssessmentComplete','final-assessment']]){if(localStorage.getItem(key)==='yes')rows.push({user_id:u.id,item_type:item.includes('checkpoint')?'checkpoint':'assessment',item_key:item,completed:true,score:item==='final-assessment'?Number(localStorage.getItem('finalAssessmentScore')||0):null,metadata:{source:'browser-import'},updated_at:new Date().toISOString()})}if(!rows.length)return {ok:true,count:0};const {error}=await kanddDb.from('progress').upsert(rows,{onConflict:'user_id,item_type,item_key'});return {ok:!error,count:error?0:rows.length,error}}
